### ISSUE TITLE
EventModel class recognized as undefined in EventController class

### ISSUE THREAD

**Issue by Tajcore** [Tajcore/Simple-MVC-Schedule#1]
The EventModel class when being instantiated in the EventController class is being recognized as an undefined entity which leads to the functions that use EventModel in EventController class to being able to use the properties of the EventModel entity

**Comment by natechris-devine** [comment]
Hmm... I think you may be having an import challenge since each of the class definitions are in different folders. I'm not seeing where in your project you're solving the import challenges.

I confess though, JavaScript importing is a hot mystery to me haha

**Comment by natechris-devine** [comment]
Perhaps you can do instantiate the app in a file in the outermost folder, and that file would import from the various folders.

My memory on how MVCs work is quite hazy, but I think that would do the trick without going against the principle

**Comment by natechris-devine** [comment]
```
class EventModel {
    event_ = {
        eventId: 0, 
        eventName: "", 
        eventDay:"",
        eventTime: "",
        eventLabTechs: []
    }

   // State of the model, the attributes of an event, prepoulated with some data
    constructor(name, day, time){
        this.event_ = 
            {
                eventId: this.event_.id + 1, 
                eventName: name, 
                eventDay: day,
                eventTime: time,
                eventLabTechs: []
            }     
    }
```

For this code, I'm assuming you're using `this.event_.id` as a static variable to be used across all instances of the class, allowing all event IDs to be unique. Would love if you could explain how it works for me though, as it would seems the static variable is intrinsically bound to each instance of `event_`, which could lead to some undesirable overwrites.

I'm not sure how well to explain this thought since JavaScript is so free-form and weird, but I think this link may help:
https://www.quora.com/How-do-you-create-static-variables-in-JavaScript/answer/Juan-Mendes-2

**Comment by Tajcore** [comment]
Thank you Nathaniel, the issue has been resolved.
